// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epyhgzjkiwkamlwdnoke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVweWhnempraXdrYW1sd2Rub2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzM1MTMsImV4cCI6MjA2NTc0OTUxM30.xzdpIT9KAnvfjIED3k-cZFh1WIAh5tC0_EpckU-v_0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);